import { Pattern } from "types/Pattern/PatternTypes";
import * as _ from "utils/durations";

export const BellPattern1: Pattern = {
  id: "pattern_preset_bell-pattern-1",
  name: "Bell Pattern 1",
  stream: [
    [_.createDottedEighthNote()],
    [_.createSixteenthNote()],
    _.createEighthRest(),
    [_.createSixteenthNote()],
    [_.createSixteenthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
    [_.createDottedEighthNote()],
    [_.createSixteenthNote()],
  ],
};
export const BellPattern2: Pattern = {
  id: "pattern_preset_bell-pattern-2",
  name: "Bell Pattern 2",
  stream: [
    [_.createDottedEighthNote()],
    [_.createSixteenthNote()],
    _.createDottedEighthRest(),
    _.createEighthRest(),
    [_.createSixteenthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
    [_.createQuarterNote()],
  ],
};
export const BellPattern3: Pattern = {
  id: "pattern_preset_bell-pattern-3",
  name: "Bell Pattern 3",
  stream: [
    [_.createDottedEighthNote()],
    [_.createSixteenthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
    [_.createQuarterNote()],
  ],
};
export const BellPattern4: Pattern = {
  id: "pattern_preset_bell-pattern-4",
  name: "Bell Pattern 4",
  stream: [
    [_.createDottedEighthNote()],
    [_.createSixteenthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
  ],
};
export const BellPattern5: Pattern = {
  id: "pattern_preset_bell-pattern-5",
  name: "Bell Pattern 5",
  stream: [
    _.createQuarterRest(),
    _.createEighthRest(),
    _.createEighthRest(),
    [_.createEighthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
    _.createEighthRest(),
    [_.createEighthNote()],
  ],
};
export const BellPattern6: Pattern = {
  id: "pattern_preset_bell-pattern-6",
  name: "Bell Pattern 6",
  stream: [
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    _.createTripletEighthRest(),
    _.createEighthRest(),
  ],
};
export const BellPattern7: Pattern = {
  id: "pattern_preset_bell-pattern-7",
  name: "Bell Pattern 7",
  stream: [
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    _.createTripletEighthRest(),
    _.createEighthRest(),
  ],
};
export const BellPattern8: Pattern = {
  id: "pattern_preset_bell-pattern-8",
  name: "Bell Pattern 8",
  stream: [
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
  ],
};
export const BellPattern9: Pattern = {
  id: "pattern_preset_bell-pattern-9",
  name: "Bell Pattern 9",
  stream: [
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    _.createTripletEighthRest(),
    _.createEighthRest(),
    [_.createTripletEighthNote()],
    _.createTripletEighthRest(),
    _.createEighthRest(),
    _.createTripletEighthRest(),
    _.createEighthRest(),
  ],
};

export default {
  BellPattern1,
  BellPattern2,
  BellPattern3,
  BellPattern4,
  BellPattern5,
  BellPattern6,
  BellPattern7,
  BellPattern8,
  BellPattern9,
};
