export const defaultProject = {
  meta: {
    id: "project-" + Math.random().toString(36).substring(2, 16),
    name: "New Project",
    dateCreated: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    diary: Array(10).fill(""),
  },
  tracks: { entities: {}, ids: [] },
  clips: { entities: {}, ids: [] },
  scales: { entities: {}, ids: [] },
  instruments: { entities: {}, ids: [] },
  patterns: { entities: {}, ids: [] },
  poses: { entities: {}, ids: [] },
  portals: { entities: {}, ids: [] },
  timeline: {
    state: "idle",
    type: "pattern",
    draft: {
      patternClip: {},
      poseClip: {},
      portal: {},
    },
    clipboard: { clips: [], portals: [] },
    selection: { clipIds: [], portalIds: [] },
    subdivision: "16n",
    cellWidth: 25,
    cellHeight: 120,
  },
  transport: {
    state: "stopped",
    bpm: 120,
    loop: false,
    loopStart: 0,
    loopEnd: 383,
    volume: 0,
    swing: 0,
    mute: false,
    timeSignature: 4,
  },
};
